spring:
  application:
    name: EmpMicroservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emp_dept?useSSL=false&serverTimezone=Asia/Dhaka&useLegacyDatetimeCode=false
    username: root
    password: 1234
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8071

